[package]
name = "gatodown"
version = "1.0.0"
authors = ["Charles Tabor <chastabor@protonmail.com>"]
edition = "2018"

[profile.release]
lto = true

[dependencies]
warp = "0.2.0"
tokio = { version = "0.2", features = ["full"] }
log = "0.4"
pretty_env_logger = "0.3"
lazy_static = "1.4.0"
